---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    custom_resource: "{{ lookup('file', '/'.join([deploy_dir, 'controller.yml'])) | from_yaml }}"

  tasks:
  - name: Create the migration.openshift.io/v1alpha1.MigrationController
    k8s:
      state: absent
      namespace: '{{ controller_namespace }}'
      definition: '{{ custom_resource }}'
      wait: yes
