apiVersion: migration.openshift.io/v1alpha1
kind: MigrationController
metadata:
  name: migration-controller
  namespace: openshift-migration
spec:
  migration_velero: true
  migration_log_reader: true
  restic_timeout: 1h
